### ISSUE TITLE
Regression: array[string] is not getting rendered correctly

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/drafter#142]
# Example

```apib
FORMAT: 1A

# Example

# GET /
+ Response 200 (application/json)
    + Attributes (object)
        + a (array[string])
            + b
            + c
```

# Old behaviour
Response body is rendered as

```json
{"a": ["b", "c"]}
```

# New behaviour
Response body is rendered as

```json
{"a": ["", "b", "c"]}
```

# Expected
Old behaviour is correct.

**Comment by kylef** [comment]
After looking into this one, it seems that the empty nested type is being added from [`RefractElementFromValue` when calling `ExtractValueMember`](https://github.com/apiaryio/drafter/blob/5837a5bc3d088a35da84b3c6c7984d182e9885aa/src/RefractDataStructure.cc#L512).

The following diff would solve the problem, although this effect is actually intentional elsewhere and causes the `test/fixtures/mson/array-typed-content` fixture to fail.

```diff
diff --git a/src/RefractDataStructure.cc b/src/RefractDataStructure.cc
index ba88e0d..e6dbc4f 100644
--- a/src/RefractDataStructure.cc
+++ b/src/RefractDataStructure.cc
@@ -363,8 +364,10 @@ namespace drafter {

                     RefractElements types;
                     for (mson::TypeNames::const_iterator it = nestedTypes.begin() ; it != nestedTypes.end(); ++it) {
-                        RefractElementFactory& f = FactoryFromType(it->base);
-                        types.push_back(f.Create(it->symbol.literal, it->symbol.variable));
+                          if (!it->symbol.empty()) {
+                            RefractElementFactory& f = FactoryFromType(it->base);
+                            types.push_back(f.Create(it->symbol.literal, it->symbol.variable));
+                        }
                     }

                     values.push_back(types);
```

Anyone have some pointers on how to proceed?

**Comment by pksunkara** [comment]
I think this is not the correct fix. There are two conditions here:

1. If nested type is primitive type, don't add it to content.
2. If nested type is non-primitive, add it to content.
