### ISSUE TITLE
drafter.js is not available in npm package

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/drafter#177]
Looks like the only distribution file in the npm package is `drafter.nomem.js`
Would it be possible to provide also the mem file and pure js file?

**Comment by obihann** [comment]
Drafter.js is actually deprecated, [protagonist](https://github.com/apiaryio/protagonist) is the official Node.js replacement for it.

**Comment by IvanGoncharov** [comment]
@obihann  [README](https://github.com/apiaryio/drafter#drafterjs) say different thing:
> Note: drafter.js is work in progress, use only for experimental purposes

You probable confusing it with [this](https://github.com/apiaryio/drafter.js) project, but it was published as `drafter` and not as `drafter.js` NPM package.

**Comment by obihann** [comment]
@IvanGoncharov yes, I thought he was referring to apiaryio/drafter.js, my mistake.

**Comment by XVincentX** [comment]
Yes, I am talking about the new generated from c++ code.

**Comment by pksunkara** [comment]
Looks like it is being ignored by npmignore. https://github.com/apiaryio/drafter/blob/master/.npmignore#L10

I don't know what's the difference between the mem and non-mem file. Maybe @danielgtaylor or @w-vi can answer it.

**Comment by w-vi** [comment]
Well the  `drafter.nomem.js` is single file which has all it needs ideal for node.js as otherwise it is not very convenient to use it. So that's why it is in npm. For browser usage you should go with the `mem` version as that makes it little bit faster to load, memory is statically initialized through the `mem` file. I didn't know that npm packages are used on the front end as well but aparently they are so we will include the `mem` and `drafter.js` files in the npm as well.
