### ISSUE TITLE
carriage return(s) problem

### ISSUE THREAD

**Issue by hardikbeladiya** [apiaryio/drafter#479]
I build drafter from the stable 3.x branch in visual studio 2017 and When I run "drafter -f json blueprint.apib" command with specifying the  blueprint.apib file i got below error
'error: (2)  the use of carriage return(s) '\r' in source data isn't currently supported, please contact makers :10:1'. Please help me as I am stuck in this around 3 days.
Thank you.

**Comment by kylef** [comment]
Hi @hardikbeladiya 

That is correct, using carriage returns is not supported in any current versions of the parser. We would suggest at the moment you use just new lines instead of carriage returns.

There is an existing issue to track adding support to the parser for carriage return support that can be tracked at https://github.com/apiaryio/snowcrash/issues/29.
