### ISSUE TITLE
Fixed-type doesn't work as expected for arrays of objects

### ISSUE THREAD

**Issue by fgblomqvist** [apiaryio/drafter#665]
```
+ Response 200 (application/json)
    + Attributes (array, required, fixed-type)
        + (Major, fixed-type)
```
and this
```
+ Response 200 (application/json)
    + Attributes (array[Major], required, fixed-type)
```
should produce the same JSON Schema imo, but they don't.

The first one produces this:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "number"
      },
      "name": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "name"
    ],
    "additionalProperties": false
  }
}
```
while the second one produces this
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "number"
      },
      "name": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "name"
    ]
  }
}
```
As you can see, the second one lacks the `additionalProperties: false`. Is there any reason to why they do not produce the same (strict) JSON Schema?

**Comment by kylef** [comment]
Coming back to this, I don't think it is a bug but expected behaviour. I'd note that unlike `fixed`, the `fixed-type` attribute is not inherited. In the first example, you've said that the array has a `fixed-type` of `Major` and then `Major` itself is fixed-type and thus it cannot have additional properties.

In the other example, only the array is `fixed-type`. The following is equivilent to the first example, where I've moved `fixed-type` to the Major definition too:

```apib
# My API

# GET /

+ Response 200 (application/json)
    + Attributes (array[Major], required, fixed-type)

## Data Structures

### Major (fixed-type)

+ name
```

**Comment by fgblomqvist** [comment]
Alright that makes sense. Not sure if I was aware of the ability of putting ’fixed-type’ on an object/data structure at the time (since this was about a year ago), but makes sense to me now. So yeah, thanks!
